#!/usr/bin/env python3
"""
update_readme.py
================
Scans the tutorials/ directory and regenerates the "Tutorials & Passages" section
in README.md between the markers:

    <!-- TUTORIALS:START -->
    ...
    <!-- TUTORIALS:END -->

Usage (run from any location — the script locates the repo root automatically):
    python .copilot/skills/update-readme/scripts/update_readme.py

Adding a new article
--------------------
1. Drop a .md file into the correct tier/topic folder, e.g.
       tutorials/tier1/python/2026-03-06-my-article.md
2. Start the file with a top-level heading  (#  My Article Title)
3. Run this script — README.md is updated automatically.
"""

import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths  (script lives at .copilot/skills/update-readme/scripts/update_readme.py)
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
README_PATH = REPO_ROOT / "README.md"
TUTORIALS_ROOT = REPO_ROOT / "tutorials"

GITHUB_BASE = (
    "https://github.com/boycececil666gmailcom/boycececil666gmailcom/blob/master"
)

START_MARKER = "<!-- TUTORIALS:START -->"
END_MARKER = "<!-- TUTORIALS:END -->"

# ---------------------------------------------------------------------------
# Display labels
# ---------------------------------------------------------------------------
TIER_LABELS = {
    "tier1": "Tier 1 \u2014 Primary Focus",
    "tier2": "Tier 2 \u2014 Building Experience",
    "tier3": "Tier 3 \u2014 Exploring",
}

TOPIC_LABELS = {
    "python": "Python",
    "csharp": "C#",
    "unity": "Unity",
    "blender": "Blender",
    "photoshop": "Photoshop",
    "git": "Git",
    "mcp": "MCP",
    "stable-diffusion": "Stable Diffusion",
    "unreal-engine": "Unreal Engine",
    "javascript": "JavaScript",
    "ros2": "ROS 2",
    "html": "HTML",
    "godot": "Godot",
    "ethereum": "Ethereum",
    "raspberry-pi": "Raspberry Pi",
    "stm32": "STM32",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def get_md_title(filepath: Path) -> str:
    """Return the first H1 heading from a markdown file, or a prettified stem."""
    try:
        for line in filepath.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()
    except OSError:
        pass
    return filepath.stem.replace("-", " ").replace("_", " ").title()


def build_tutorials_section() -> str:
    """Build the complete Tutorials & Passages markdown block."""
    lines: list[str] = [
        "## Tutorials & Passages \u2014 *by expertise tier*",
        "",
        "> Auto-generated by `update_readme.py` \u2014 do not edit this block manually.",
        "",
    ]

    any_content = False

    for tier in ("tier1", "tier2", "tier3"):
        tier_path = TUTORIALS_ROOT / tier
        if not tier_path.is_dir():
            continue

        topic_blocks: list[list[str]] = []

        for topic_dir in sorted(tier_path.iterdir()):
            if not topic_dir.is_dir():
                continue

            # Collect articles — skip _index.md and other underscore files
            articles = sorted(
                f for f in topic_dir.glob("*.md") if not f.name.startswith("_")
            )
            if not articles:
                continue

            topic_label = TOPIC_LABELS.get(
                topic_dir.name,
                topic_dir.name.replace("-", " ").title(),
            )

            block: list[str] = [f"**{topic_label}**", ""]
            for article in articles:
                title = get_md_title(article)
                rel = article.relative_to(REPO_ROOT).as_posix()
                url = f"{GITHUB_BASE}/{rel}"
                block.append(f"- [{title}]({url})")
            block.append("")
            topic_blocks.append(block)

        if topic_blocks:
            any_content = True
            tier_label = TIER_LABELS.get(tier, tier)
            lines.append(f"### {tier_label}")
            lines.append("")
            for block in topic_blocks:
                lines.extend(block)

    if not any_content:
        lines.append(
            "*No tutorials published yet \u2014 drop `.md` files into any "
            "`tutorials/tier*/topic/` folder and re-run `update_readme.py`.*"
        )
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# README writer
# ---------------------------------------------------------------------------
def update_readme() -> None:
    if not README_PATH.exists():
        print(f"ERROR: {README_PATH} not found.", file=sys.stderr)
        sys.exit(1)

    readme = README_PATH.read_text(encoding="utf-8")
    section = build_tutorials_section()
    new_block = f"{START_MARKER}\n{section}\n{END_MARKER}"

    if START_MARKER in readme and END_MARKER in readme:
        updated = re.sub(
            re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
            new_block,
            readme,
            flags=re.DOTALL,
        )
    else:
        anchor = "\n---\n\n## Projects\n"
        if anchor in readme:
            updated = readme.replace(anchor, f"\n{new_block}\n{anchor}", 1)
        else:
            updated = readme.rstrip() + f"\n\n{new_block}\n"

    README_PATH.write_text(updated, encoding="utf-8")
    print("README.md updated \u2014 tutorials section regenerated.")


if __name__ == "__main__":
    update_readme()
